### ISSUE TITLE
[Migration] Migrate all JAX models

### ISSUE THREAD

**Issue by pzread** [openxla/openxla-benchmark#34]
Migrate the rest of JAX models from https://github.com/iree-org/iree-samples/blob/main/oobi/benchmark-definitions/python/jax_model_definitions.py

- [x] RESNET50_FP32_JAX (Done by #43)
- [x] RESNET50_FP16_JAX (Done by #43)
- [x] RESNET50_BF16_JAX (Done by #43)
- [x] BERT_LARGE_FP32_JAX (Done by #42)
- [x] BERT_LARGE_FP16_JAX (Done by #42)
- [x] BERT_LARGE_BF16_JAX (Done by #42)
- [x] T5_LARGE_FP32_JAX
- [x] T5_LARGE_FP16_JAX (Done by #53)
- [x] T5_LARGE_BF16_JAX (Done by #53)
